# Generated by Django 5.0.3 on 2024-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0002_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plec',
            field=models.IntegerField(choices=[(0, 'Mężczyzna'), (1, 'Kobieta')]),
        ),
    ]
