# Generated by Django 5.0.3 on 2024-03-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0003_alter_user_plec'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edytowany',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='utworzony',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
