# Generated by Django 5.0.3 on 2024-03-14 12:53

import uzytkownicy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0005_alter_user_edytowany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edytowany',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pesel',
            field=models.CharField(max_length=11, unique=True, validators=[uzytkownicy.validators.validate_pesel]),
        ),
        migrations.AlterField(
            model_name='user',
            name='utworzony',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
