# Generated by Django 5.0.3 on 2024-03-18 17:14

import django.core.validators
import uzytkownicy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0006_alter_user_edytowany_alter_user_pesel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_urodzenia',
            new_name='Data_urodzenia',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pesel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plec',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefon',
        ),
        migrations.DeleteModel(
            name='Adres',
        ),
        migrations.AddField(
            model_name='user',
            name='Pesel',
            field=models.CharField(default='111111111', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='PESEL musi mieć 11 znaków.', regex='^\\d{11}$'), uzytkownicy.validators.validate_pesel]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Plec',
            field=models.BooleanField(choices=[(0, 'Męźczyzna'), (1, 'Kobieta')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Telefon',
            field=models.CharField(default=1, max_length=9, validators=[django.core.validators.RegexValidator(message='Niepoprawny numer telefonu', regex='^\\d{9}$')]),
            preserve_default=False,
        ),
    ]
