# Generated by Django 5.0.3 on 2024-03-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0007_rename_data_urodzenia_user_data_urodzenia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Plec',
            field=models.IntegerField(choices=[(0, 'Męźczyzna'), (1, 'Kobieta')]),
        ),
    ]
