# Generated by Django 5.0.3 on 2024-04-15 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0008_alter_user_plec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_books', models.BooleanField()),
                ('Delete_books', models.BooleanField()),
                ('Edit_books', models.BooleanField()),
                ('Detail_book', models.BooleanField()),
                ('Add_user', models.BooleanField()),
                ('Delete_user', models.BooleanField()),
                ('Edit_user', models.BooleanField()),
                ('List_user', models.BooleanField()),
                ('Detail_user', models.BooleanField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
