# Generated by Django 5.0.3 on 2024-04-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0009_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='Add_books',
            field=models.BooleanField(default=False, verbose_name='Dodawanie książek'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='Add_user',
            field=models.BooleanField(default=False, verbose_name='Dodawanie użytkownika'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='Delete_books',
            field=models.BooleanField(default=False, verbose_name='Usuwanie książek'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='Delete_user',
            field=models.BooleanField(default=False, verbose_name='Usuwanie użytkownika'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='Detail_book',
            field=models.BooleanField(default=False, verbose_name='Detale książki'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='Detail_user',
            field=models.BooleanField(default=False, verbose_name='Detale użytkownika'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='Edit_books',
            field=models.BooleanField(default=False, verbose_name='Edytowanie książek'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='Edit_user',
            field=models.BooleanField(default=False, verbose_name='Edytowanie użytkownika'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='List_user',
            field=models.BooleanField(default=False, verbose_name='Listowanie użytkowników'),
        ),
    ]
