# Generated by Django 5.0.3 on 2024-04-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0010_alter_permissions_add_books_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='UserID',
            new_name='User',
        ),
    ]
