# Generated by Django 5.0.3 on 2024-04-21 18:20

import uzytkownicy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0011_rename_userid_permissions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_db',
            field=models.CharField(default=1, max_length=15, validators=[uzytkownicy.validators.password_validator]),
            preserve_default=False,
        ),
    ]
