# Generated by Django 5.0.3 on 2024-04-21 19:56

import uzytkownicy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0012_user_password_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generated_password',
            field=models.CharField(default=1, max_length=15, validators=[uzytkownicy.validators.password_validator]),
            preserve_default=False,
        ),
    ]
