# Generated by Django 5.0.3 on 2024-04-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0014_alter_permissions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwords_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
