# Generated by Django 5.0.3 on 2024-05-03 13:52

import uzytkownicy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0015_user_passwords_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_db',
            new_name='current_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='generated_password',
            new_name='password_1',
        ),
        migrations.AddField(
            model_name='user',
            name='password_2',
            field=models.CharField(default='NoweHasło1!', max_length=15, validators=[uzytkownicy.validators.password_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password_3',
            field=models.CharField(default='NoweHasło1!@', max_length=15, validators=[uzytkownicy.validators.password_validator]),
            preserve_default=False,
        ),
    ]
