# Generated by Django 5.0.3 on 2024-05-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0017_user_is_password_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pracownik',
            new_name='Bibliotekarz',
        ),
        migrations.AddField(
            model_name='user',
            name='ManagerBiblioteki',
            field=models.BooleanField(default=False),
        ),
    ]
