# Generated by Django 5.0.3 on 2024-05-10 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0018_rename_pracownik_user_bibliotekarz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
