# Generated by Django 5.0.3 on 2024-05-06 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egzemplarze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stan', models.IntegerField(choices=[(0, 'Dostępna'), (1, 'Wyporzyczona')])),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tytul', models.CharField(max_length=100)),
                ('Autor', models.CharField(max_length=50)),
                ('Gatunek', models.IntegerField(choices=[(1, 'Literatura Piękna'), (2, 'Literatura Faktu'), (3, 'Kryminał'), (4, 'Fantastyka'), (5, 'Biografia'), (6, 'Literatura Historyczna'), (7, 'Romans'), (8, 'Literatura Naukowa'), (9, 'Dramat'), (10, 'Literatura Przygodowa')])),
                ('Liczba_stron', models.IntegerField()),
                ('Wydawnictwo', models.CharField(max_length=50)),
                ('Rok_wydania', models.IntegerField()),
                ('Cena', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Liczba_ezamplarzy', models.IntegerField()),
                ('Opis', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('Okres', models.IntegerField()),
                ('Data_zwrotu', models.DateField()),
                ('Stan', models.IntegerField(choices=[(0, 'Nowe'), (1, 'Stare'), (2, 'Przedłużone'), (3, 'Po terminie'), (4, 'Zakończone')])),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='egzemplarze',
            name='KsiazkaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotekarz.ksiazki'),
        ),
        migrations.AddField(
            model_name='wypozyczenia',
            name='EgzemplarzeIDs',
            field=models.ManyToManyField(to='bibliotekarz.egzemplarze'),
        ),
        migrations.AddField(
            model_name='wypozyczenia',
            name='KlientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wypozyczenia',
            name='PracownikID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pracownik', to=settings.AUTH_USER_MODEL),
        ),
    ]
