# Generated by Django 5.0.3 on 2024-05-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0002_egzemplarze_ksiazki_wypozyczenia_delete_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wypozyczenia',
            name='Okres',
        ),
        migrations.AlterField(
            model_name='egzemplarze',
            name='Stan',
            field=models.IntegerField(choices=[(0, 'Dostępna'), (1, 'Wypozyczona')]),
        ),
    ]
