# Generated by Django 5.0.3 on 2024-05-10 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0003_remove_wypozyczenia_okres_alter_egzemplarze_stan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ksiazki',
            name='Gatunek',
        ),
        migrations.AlterField(
            model_name='wypozyczenia',
            name='Data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wypozyczenia',
            name='Data_zwrotu',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='wypozyczenia',
            name='Stan',
            field=models.IntegerField(choices=[(0, 'Nowe'), (1, 'Przedłużone'), (2, 'Po terminie'), (3, 'Zakończone')]),
        ),
        migrations.CreateModel(
            name='Rejestracje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('EgzemplarzeIDs', models.ManyToManyField(to='bibliotekarz.egzemplarze')),
                ('PracownikID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pracownik_rejestracje', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ksiazki',
            name='Gatunek',
            field=models.ManyToManyField(to='bibliotekarz.gatunki'),
        ),
    ]
