# Generated by Django 5.0.3 on 2024-05-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0005_remove_ksiazki_gatunek_ksiazki_gatunek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ksiazki',
            old_name='Liczba_ezamplarzy',
            new_name='Liczba_egzamplarzy',
        ),
    ]
