# Generated by Django 5.0.3 on 2024-05-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0006_rename_liczba_ezamplarzy_ksiazki_liczba_egzamplarzy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejestracje',
            name='EgzemplarzeIDs',
        ),
        migrations.RemoveField(
            model_name='wypozyczenia',
            name='EgzemplarzeIDs',
        ),
        migrations.AddField(
            model_name='ksiazki',
            name='Stan',
            field=models.IntegerField(choices=[(0, 'Dostępna'), (1, 'Wypozyczona')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rejestracje',
            name='KsiazkaID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibliotekarz.ksiazki'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wypozyczenia',
            name='KsiazkaID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibliotekarz.ksiazki'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Egzemplarze',
        ),
    ]
