# Generated by Django 5.0.3 on 2024-05-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0007_remove_rejestracje_egzemplarzeids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazki',
            name='Stan',
            field=models.IntegerField(choices=[('dostepna', 'Dostępna'), ('wypozyczona', 'Wypozyczona')]),
        ),
    ]
