# Generated by Django 5.0.3 on 2024-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0008_alter_ksiazki_stan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazki',
            name='Stan',
            field=models.CharField(choices=[('Dostępna', 'Dostępna'), ('Wypożyczona', 'Wypozyczona')], max_length=20),
        ),
    ]
