# Generated by Django 5.0.3 on 2024-05-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0009_alter_ksiazki_stan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wypozyczenia',
            name='Data',
        ),
        migrations.RemoveField(
            model_name='wypozyczenia',
            name='Data_zwrotu',
        ),
    ]
