# Generated by Django 5.0.3 on 2024-05-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0010_remove_wypozyczenia_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wypozyczenia',
            name='Data',
            field=models.DateField(default='2024-05-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wypozyczenia',
            name='Data_zwrotu',
            field=models.DateField(default='2024-05-24'),
            preserve_default=False,
        ),
    ]
