# Generated by Django 5.0.3 on 2024-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0011_wypozyczenia_data_wypozyczenia_data_zwrotu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazki',
            name='Liczba_egzamplarzy',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='Liczba_stron',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='Rok_wydania',
            field=models.PositiveIntegerField(),
        ),
    ]
