# Generated by Django 5.0.3 on 2024-05-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0013_ksiazki_utworzone_przez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazki',
            name='Cena',
            field=models.PositiveIntegerField(),
        ),
    ]
