# Generated by Django 5.0.3 on 2024-05-20 09:25

import bibliotekarz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0014_alter_ksiazki_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazki',
            name='Liczba_dostepnych_egzemplarzy',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='Cena',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[bibliotekarz.models.positive_decimal]),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='Tytul',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
