# Generated by Django 5.0.3 on 2024-05-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0015_ksiazki_liczba_dostepnych_egzemplarzy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazki',
            name='Tytul',
            field=models.CharField(max_length=100),
        ),
    ]
