# Generated by Django 5.0.6 on 2024-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0016_alter_ksiazki_tytul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazki',
            name='Tytul',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='wypozyczenia',
            name='Data_zwrotu',
            field=models.DateField(null=True),
        ),
    ]
