# Generated by Django 5.0.6 on 2024-06-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotekarz', '0017_alter_ksiazki_tytul_alter_wypozyczenia_data_zwrotu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wypozyczenia',
            name='Data_zwrotu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wypozyczenia',
            name='Stan',
            field=models.CharField(choices=[('Nowe', 'Nowe'), ('Przedłużone', 'Przedłużone'), ('Po terminie', 'Po terminie'), ('Zakończone', 'Zakończone')], max_length=100),
        ),
    ]
